[package]
name = "trash"
version = "1.0.0"
authors = ["Artur Kovacs <kovacs.artur.barnabas@gmail.com>"]
license = "MIT"
readme = "Readme.md"
description = "A Rust library for moving files to the Recycle Bin"
keywords = ["remove", "trash", "rubbish", "recycle", "bin"]
repository = "https://github.com/ArturKovacs/trash"
edition = "2018"

[features]
default = ["coinit_apartmentthreaded"]
coinit_apartmentthreaded = []
coinit_multithreaded = []
coinit_disable_ole1dde = []
coinit_speed_over_memory = []

[dev-dependencies]
chrono = "0.4.9"
rand = "0.7.2"
lazy_static = "1.4.0"

[dependencies]

[target.'cfg(windows)'.dependencies]
scopeguard = "1.0.0"

[target.'cfg(windows)'.dependencies.winapi]
git = "https://github.com/ArturKovacs/winapi-rs.git"
rev = "fe297b9830c804b274e2206d3aebfe9dc33e39cb"
features = [
    "combaseapi", "objbase", "shlobj", "shellapi", "winerror", "shlobj", "shlwapi", "shobjidl_core",
    "shobjidl", "oleauto", "oaidl", "wtypes", "errhandlingapi", "timezoneapi", "winuser"
]
